- name: Pure Storage storage module examples
  hosts: localhost
  gather_facts: false
  vars:
    url: 10.10.10.10
    api: T-9f276a18-xxxx-yyyy-8a0c-666a3529a1b6
  tasks:
    - name: Create s3 account
      purestorage.flashblade.purefb_s3acc:
        name: foo
        fb_url: "{{ url }}"
        api_token: "{{ api }}"

    - name: Create s3 user
      purestorage.flashblade.purefb_s3user:
        name: bar
        account: foo
        fb_url: "{{ url }}"
        api_token: "{{ api }}"
      register: user_info

    - name: Debug response
      ansible.builtin.debug:
        var: user_info.s3user_info.fb_s3user

    - name: Create bucket
      purestorage.flashblade.purefb_bucket:
        name: testbucket
        account: foo
        fb_url: "{{ url }}"
        api_token: "{{ api }}"
