---
# tasks file for pure_fb_filesystem_failback
- name: Failback | Include task for failback
  ansible.builtin.include_tasks: failback.yml repl_vars={{ repl_loop.value }}
  loop: "{{ fsreplication | dict2items }}"
  loop_control:
    loop_var: repl_loop
