---
- name: Create a host and attach volume
  hosts: cloudblockstore
  connection: local
  gather_facts: no
  collections:
  - purestorage.flasharray
  vars:
    ansible_python_interpreter: auto

  tasks:
    - name: attach volume to existing host
      purefa_host:
        host: "{{ hostvars[cloud_initiator]['ansible_hostname'] }}"
        volume: "{{ volname }}"
        fa_url: "{{ fa_url }}"
        api_token: "{{ pure_api_token }}"
