---
- name: Combine CBS Storage Provisioning Playbooks
  hosts: all
  connection: local
  gather_facts: no

# Linux OS Playbooks For iSCSI Installation

- import_playbook: collect-cbs-facts.yaml
- import_playbook: create-cbs-volume.yaml
- import_playbook: install-iscsi-linux.yaml
- import_playbook: create-cbs-host-linux.yaml
- import_playbook: login-iscsi-linux.yaml
- import_playbook: enable-mpio-linux.yaml
