---
- name: Create a host and attach volume
  hosts: cloudblockstore
  connection: local
  gather_facts: no
  collections:
  - purestorage.flasharray
  vars:
    ansible_python_interpreter: auto
  
  tasks:
    - name: create a new host and attach volume
      purefa_host:
        host: "{{ hostvars[cloud_initiator]['ansible_hostname'] }}"
        volume: "{{ volname }}"
        iqn: "{{ hostvars[cloud_initiator]['iqn']['stdout'] }}"
        fa_url: "{{ fa_url }}"
        api_token: "{{ pure_api_token }}"
