---
- hosts: "{{ cloud_initiator }}" 
  become: true
  gather_facts: yes
  vars:
    ansible_python_interpreter: auto

  tasks:
 
        - name: Create iSCSI interfaces
          shell:
            cmd: iscsiadm -m iface -I iscsi1 -o new

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\12/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 1

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\12/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 2

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\12/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 4

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\14/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 8

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\18/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 16

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\116/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 32

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\118/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 36

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\120/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 40

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\124/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 48

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\132/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 64

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\132/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 72

        - name: Modify iscsid Session Count
          shell:
            cmd: sed -i 's/^\(node\.session\.nr_sessions\s*=\s*\).*$/\132/' /etc/iscsi/iscsid.conf
            warn: false
          when: ansible_processor_vcpus == 96

        - name: Discover Target Portals
          shell:
            cmd: iscsiadm -m discovery -t st -p "{{ hostvars.cloudblockstore.iscsiportalct0ipport.stdout }}"

        - name: Login CT0
          shell:
            cmd: iscsiadm -m node -p "{{ hostvars.cloudblockstore.iscsiportalct0ip.stdout }}" --login

        - name: Login CT1
          shell:
            cmd: iscsiadm -m node -p "{{ hostvars.cloudblockstore.iscsiportalct1ip.stdout }}" --login

        - name: Add automatic node connection startup for ct0 Pure targets only
          shell:
            cmd: iscsiadm --mode node -T "{{ hostvars.cloudblockstore.iqn.stdout }}" -p "{{ hostvars.cloudblockstore.iscsiportalct0ipport.stdout }}" -o update -n node.conn[0].startup -v automatic

        - name: Add automatic node connection startup for ct1 Pure targets only
          shell:
            cmd: iscsiadm --mode node -T "{{ hostvars.cloudblockstore.iqn.stdout }}" -p "{{ hostvars.cloudblockstore.iscsiportalct1ipport.stdout }}" -o update -n node.conn[0].startup -v automatic
