---
- name: List consumer items
  hosts: localhost
  tasks:
    - name: Import consumer variables
      ansible.builtin.include_vars: group_vars/consumer.yml

    - name: Setup local variables
      ansible.builtin.set_fact:
        tenants_dict: {}

    - name: Get tenants
      purestorage.fusion.fusion_info:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        gather_subset: tenants
      register: fusion_info

    - name: Print tenants
      ansible.builtin.debug:
        msg: "{{ fusion_info['fusion_info'] }}"

    - name: Get tenant_spaces
      purestorage.fusion.fusion_info:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        gather_subset: tenant_spaces
      register: fusion_info

    - name: Print tenant spaces
      ansible.builtin.debug:
        msg: "{{ fusion_info['fusion_info'] }}"
