---

- name: Teardown protection policies
  hosts: localhost
  tasks:
    - name: Import protection policy variables
      ansible.builtin.include_vars: group_vars/protection_policies.yml

    - name: Check private key exists
      ansible.builtin.stat:
        path: "{{ private_key_file }}"
      register: result

    - name: End run if missing private key
      ansible.builtin.meta: end_play
      when: (result.stat.isreg is undefined) or (not result.stat.isreg)

    - name: Delete protection policy(s)
      purestorage.fusion.fusion_pp:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        name: "{{ item.name }}"
      loop: "{{ protection_policy }}"
