---

- name: Teardown protection policies
  hosts: localhost
  tasks:
    - name: Import storage service/class variables
      ansible.builtin.include_vars: group_vars/storage_service_class.yml

    - name: Check private key exists
      ansible.builtin.stat:
        path: "{{ private_key_file }}"
      register: result

    - name: End run if missing private key
      ansible.builtin.meta: end_play
      when: (result.stat.isreg is undefined) or (not result.stat.isreg)

    - name: Delete storage class
      purestorage.fusion.fusion_sc:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        name: "{{ item.name }}"
        storage_service: "{{ item.storage_service }}"
      loop: "{{ storage_class }}"

    - name: Delete storage service
      purestorage.fusion.fusion_ss:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        name: "{{ item.name }}"
      loop: "{{ storage_service }}"
