---
- name: Setup volume live migration
  hosts: localhost
  tasks:
    - name: Import storage volume variables
      ansible.builtin.include_vars: group_vars/storage_service_class.yml

    - name: Check private key exists
      ansible.builtin.stat:
        path: "{{ private_key_file }}"
      register: result

    - name: End run if missing private key
      ansible.builtin.meta: end_play
      when: (result.stat.isreg is undefined) or (not result.stat.isreg)
    
    - name: Delete Volume A
      purestorage.fusion.fusion_volume:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        eradicate: true
        name: Volume-A
        tenant: Tenant-A
        tenant_space: Tenant-Space-A
    
    - name: Delete Volume B
      purestorage.fusion.fusion_volume:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        eradicate: true
        name: Volume-B
        tenant: Tenant-A
        tenant_space: Tenant-Space-A

    - name: Delete placement group A
      purestorage.fusion.fusion_pg:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        name: pg-A
        tenant: Tenant-A
        tenant_space: Tenant-Space-A
        destroy_snapshots_on_delete: true

    - name: Delete storage class A
      purestorage.fusion.fusion_sc:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        name: storage-class-A
        storage_service: storage-service-A

    - name: Delete storage class B
      purestorage.fusion.fusion_sc:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        name: storage-class-B
        storage_service: storage-service-A

    - name: Delete Storage Service A
      purestorage.fusion.fusion_ss:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        name: storage-service-A

    - name: Delete Availability Zone
      purestorage.fusion.fusion_az:
        issuer_id: "{{ issuer_id }}"
        private_key_file: "{{ private_key_file }}"
        state: absent
        name: AZ-1
        region: pure-us-west
