---
# tasks file for pure_fb_filesystem_failover
- name: Failover | Include task for failover
  ansible.builtin.include_tasks: failover.yml repl_vars={{ repl_loop.value }}
  loop: "{{ fsreplication | dict2items }}"
  loop_control:
    loop_var: repl_loop
