---
- name: Install nfs-utils and mount filesystems on clients
  block:
  - name: packages | Install nfs-utils package
    include: packages.yml

  - name: mount | Unmout all the clients from src and mount back to dst filesystem
    mount:
      path: "{{ mount.mount_point }}"
      state: mounted
      fstype: nfs
      src: "{{ dst_data_vip }}:/{{ dst_fileshare }}"
    become: true
  when: mount.hosts in group_names or mount.hosts == inventory_hostname or mount.hosts == ansible_hostname
