---
- name: Install nfs-utils and mount filesystems on clients
  when: mount.hosts in group_names or mount.hosts == inventory_hostname or mount.hosts == ansible_hostname
  block:
    - name: Packages | Install nfs-utils package
      ansible.builtin.include_tasks: packages.yml
    - name: Opts | Get mount options from existing File System mount
      ansible.builtin.set_fact:
        mount_opts: "{{ item.options }}"
      loop: "{{ ansible_mounts }}"
      when: item.mount == mount.mount_point
      loop_control:
        label: "{{ item.mount }}"

    - name: Unmount | Unmout all the clients from source File System
      ansible.posix.mount:
        path: "{{ mount.mount_point }}"
        state: absent
      become: true

    - name: Mount | Mount clients back to the destination File System
      ansible.posix.mount:
        path: "{{ mount.mount_point }}"
        state: mounted
        fstype: nfs
        opts: "{{ mount_opts | default(omit) }}"
        src: "{{ dst_data_vip }}:/{{ dst_fileshare }}"
      become: true
