---
- name: Validation | Check connectivity for FBServer
  ansible.builtin.command: ping -q -c 4 -W 1 {{ fb_vars.fb_host }}
  register: fb_ping_status
  failed_when: false
  changed_when: false

- name: Validation | Fail if Flashblade server not reachable
  ansible.builtin.fail:
    msg: FB server {{ fb_vars.fb_host }} not reachable
  when: "'100% packet loss' in fb_ping_status.stdout"

- name: Validation | Check if reachable fb_host is FB server or not to fail fast
  ansible.builtin.uri:
    url: https://{{ fb_vars.fb_host }}/api/api_version
    method: GET
    validate_certs: false
    return_content: true
    timeout: 10
  register: api_version
  failed_when: false

- name: Validation | Fail if Flashblade server mentioned in "fb_host" is not FlashBlade server
  ansible.builtin.fail:
    msg: FB server {{ fb_vars.fb_host }} is not valid FlashBlade server
  when: (api_version.status != 200 )

- name: Setup object-store
  ansible.builtin.include_tasks: setup_object-store.yml
  loop: "{{ fb_vars.object_store | default([]) }}"
  loop_control:
    loop_var: s3_var
  when: s3_var is defined and (s3_var|default([])|length > 0)
