---
- name: Smb | Create map drive
  ansible.builtin.include_tasks: smbmount.yml mount_details={{ outer_loop.value }}
  loop: "{{ windows_client_mount | dict2items }}"
  loop_control:
    loop_var: outer_loop
