- name: Pure Storage storage module examples
  hosts: localhost
  vars:
    fb_url: 10.10.10.10
    fb_api_token: T-xxx-xxxx-xxxx-xxxxx-xxxx-xxx
  gather_facts: false
  tasks:
    - name: Get FB facts
      purestorage.flashblade.purefb_info:
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
        gather_subset: all
      register: blade_info

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ blade_info['purefb_info'] }}"

    - name: Pause
      ansible.builtin.pause:

    - name: Create test filesystem
      purestorage.flashblade.purefb_fs:
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
        name: "rules_test"
        state: present
        size: 1T
        nfsv3: true
        nfsv4: false
        hard_limit: true
        nfs_rules: '10.10.28.78/32(rw,no_root_squash)'
        snapshot: true

    - name: Create test snapshot
      purestorage.flashblade.purefb_snap:
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
        name: "rules_test"
        state: present
        suffix: "ansible-snap"

    - name: Pause
      ansible.builtin.pause:

    - name: Delete test filesystem
      purestorage.flashblade.purefb_fs:
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
        name: "rules_test"
        state: absent

    - name: Delete test filesystem
      purestorage.flashblade.purefb_fs:
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
        name: "rules_test"
        state: absent
        eradicate: true
