---
- name: FlashBlade filesystem setup
  hosts: localhost
  vars_files:
    - vars/{{ env }}/fb_details.yml
    - vars/{{ env }}/fb_secrets.yml
  roles:
    - purefb_filesystem_setup

- name: Mount SMB file share on windows hosts
  hosts: win
  gather_facts: false
  vars_files:
    - vars/{{ env }}/fb_details.yml
    - vars/{{ env }}/fb_secrets.yml
  roles:
    - purefb_smb_map
