- name: Commvault Snapshots Cleanup
  hosts: localhost
  gather_facts: yes
  vars:
    array_ip: <array_ip>
    array_api: <account_token>
  tasks:
    - name: perform the Commvault cleanup
      block:
      - name: Get all snapshot information
        purestorage.flasharray.purefa_info:
          gather_subset:
          - snapshots
          fa_url: "{{ array_ip }}"
          api_token: "{{ array_api }}"
        register: fa_snapshots
      - name: Check local Commvault related snapshots
        include_tasks: time_check.yaml
        with_items: "{{ fa_snapshots.purefa_info.snapshots | dict2items }}"
        when: '"SP-2" in item.key and item.value.is_local'
        ignore_errors: true
        no_log: true
      rescue:
      - name: No Commvault snapshots present
        ansible.builtin.debug:
          msg: "No Commvault snapshots present on array"
