---
# tasks file for pure_fb_filesystem_replication
- name: Replication | Include task for replication
  ansible.builtin.include_tasks: replication.yml repl_vars={{ repl_loop.value }}
  loop: "{{ fsreplication | dict2items }}"
  loop_control:
    loop_var: repl_loop
