---
- name: Packages | Install NFS client packages
  ansible.builtin.include_tasks: packages.yml
- name: "{{ mount_state | default('mount') }} | Create directory and do NFS mount"
  ansible.builtin.include_tasks: nfsmount.yml mount_details={{ outer_loop.value }}
  loop: "{{ linux_client_mount | dict2items }}"
  loop_control:
    loop_var: outer_loop
